---

- name: Start kibana container
  docker_container: 
    name: "{{ kibana_hostname }}"
    image: "{{ kibana_image }}"
    env: 
      servername: "{{ server_name }}"
      ELASTICSEARCH_NAME: "https://{{ elasticsearch_hostname }}:9200"
      ELASTICSEARCH_USERVENE: "kibana"
      ELASTICSEARCH_PASSWORD: "{{ kabana_password }}"
    networks:
    - name: "{{ network_name }}"
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"